In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [3]:
import polars as pl
from config.rutas import RUTA_DATA_RAW

# Carga de los Datos Crudos

In [18]:
df_crudo = pl.read_csv(RUTA_DATA_RAW / "endireh_2021.csv")
print(df_crudo.shape)
print(df_crudo.head())

(110127, 24)
shape: (5, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cve_entid ┆ nom_entid ┆ cve_munic ┆ nom_munic ┆ … ┆ propietar ┆ sufrio_vi ┆ factor_ex ┆ anio_enc │
│ ad        ┆ ad        ┆ ipio      ┆ ipio      ┆   ┆ ia_vivien ┆ olencia_p ┆ pansion   ┆ uesta    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ da_desc   ┆ areja     ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ i64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 0         ┆ 113       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 1         ┆ 113       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ No        ┆ 0         ┆ 227       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 0         ┆ 113       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 1         ┆ 155       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
lf = pl.scan_csv(RUTA_DATA_RAW / "endireh_2021.csv")
lf.collect_schema()

Schema([('cve_entidad', Int64),
        ('nom_entidad', String),
        ('cve_municipio', Int64),
        ('nom_municipio', String),
        ('edad_primer_union', Float64),
        ('num_hijos', Float64),
        ('nivel_escolaridad', String),
        ('estado_civil_id', Int64),
        ('estado_civil_desc', String),
        ('estrato_socioeconomico', Int64),
        ('pareja_trabaja_id', Int64),
        ('pareja_trabaja_desc', String),
        ('ingreso_pareja', Float64),
        ('dinero_propio_id', Int64),
        ('dinero_propio_desc', String),
        ('apoyo_gobierno_id', Int64),
        ('apoyo_gobierno_desc', String),
        ('tiene_ahorros_id', Int64),
        ('tiene_ahorros_desc', String),
        ('propietaria_vivienda_id', Int64),
        ('propietaria_vivienda_desc', String),
        ('sufrio_violencia_pareja', Int64),
        ('factor_expansion', Int64),
        ('anio_encuesta', Int64)])

In [17]:
lf.head().collect()

shape: (5, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cve_entid ┆ nom_entid ┆ cve_munic ┆ nom_munic ┆ … ┆ propietar ┆ sufrio_vi ┆ factor_ex ┆ anio_enc │
│ ad        ┆ ad        ┆ ipio      ┆ ipio      ┆   ┆ ia_vivien ┆ olencia_p ┆ pansion   ┆ uesta    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ da_desc   ┆ areja     ┆ ---       ┆ ---      │
│ i64       ┆ str       ┆ i64       ┆ str       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ i64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 0         ┆ 113       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 1         ┆ 113       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ No        ┆ 0         ┆ 227       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 0         ┆ 113       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ AGUASCALI ┆ 1         ┆ AGUASCALI ┆ … ┆ Sí        ┆ 1         ┆ 155       ┆ 2021     │
│           ┆ ENTES     ┆           ┆ ENTES     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Exploración

In [ ]:
schema = lf.collect_schema()
print("Columnas:", schema.names())
print("Cantidad de columnas:", schema.len())

n_filas = lf.select(pl.len()).collect().item()
print("Cantidad de filas:", n_filas)

Columnas: ['cve_entidad', 'nom_entidad', 'cve_municipio', 'nom_municipio', 'edad_primer_union', 'num_hijos', 'nivel_escolaridad', 'estado_civil_id', 'estado_civil_desc', 'estrato_socioeconomico', 'pareja_trabaja_id', 'pareja_trabaja_desc', 'ingreso_pareja', 'dinero_propio_id', 'dinero_propio_desc', 'apoyo_gobierno_id', 'apoyo_gobierno_desc', 'tiene_ahorros_id', 'tiene_ahorros_desc', 'propietaria_vivienda_id', 'propietaria_vivienda_desc', 'sufrio_violencia_pareja', 'factor_expansion', 'anio_encuesta']
Cantidad de columnas: 24
Cantidad de filas: 110127

In [19]:
lf.describe()

shape: (9, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ cve_entid ┆ nom_entid ┆ cve_munic ┆ … ┆ propietar ┆ sufrio_vi ┆ factor_ex ┆ anio_enc │
│ ---       ┆ ad        ┆ ad        ┆ ipio      ┆   ┆ ia_vivien ┆ olencia_p ┆ pansion   ┆ uesta    │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ da_desc   ┆ areja     ┆ ---       ┆ ---      │
│           ┆ f64       ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 110127.0  ┆ 110127    ┆ 110127.0  ┆ … ┆ 110127    ┆ 110127.0  ┆ 110127.0  ┆ 110127.0 │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 16.553861 ┆ null      ┆ 38.830178 ┆ … ┆ null      ┆ 0.175307  ┆ 458.77458 ┆ 2021.0   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆          │
│ std       ┆ 9.205016  ┆ null      ┆ 62.274657 ┆ … ┆ null      ┆ 0.380231  ┆ 513.05562 ┆ 0.0      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆          │
│ min       ┆ 1.0       ┆ AGUASCALI ┆ 1.0       ┆ … ┆ No        ┆ 0.0       ┆ 12.0      ┆ 2021.0   │
│           ┆           ┆ ENTES     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 9.0       ┆ null      ┆ 7.0       ┆ … ┆ null      ┆ 0.0       ┆ 172.0     ┆ 2021.0   │
│ 50%       ┆ 17.0      ┆ null      ┆ 19.0      ┆ … ┆ null      ┆ 0.0       ┆ 296.0     ┆ 2021.0   │
│ 75%       ┆ 25.0      ┆ null      ┆ 44.0      ┆ … ┆ null      ┆ 0.0       ┆ 554.0     ┆ 2021.0   │
│ max       ┆ 32.0      ┆ ZACATECAS ┆ 570.0     ┆ … ┆ Sí        ┆ 1.0       ┆ 8836.0    ┆ 2021.0   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Valores nulos

In [20]:
lf.null_count().collect()

shape: (1, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ cve_entid ┆ nom_entid ┆ cve_munic ┆ nom_munic ┆ … ┆ propietar ┆ sufrio_vi ┆ factor_ex ┆ anio_enc │
│ ad        ┆ ad        ┆ ipio      ┆ ipio      ┆   ┆ ia_vivien ┆ olencia_p ┆ pansion   ┆ uesta    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ da_desc   ┆ areja     ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ ---       ┆ ---       ┆ u32       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆ u32       ┆ u32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘